server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5

redis:
  maxTotal: 8
  maxIdle: 8
  minIdle: 0
  blockWhenExhausted: true
  maxWaitMillis: 10000
  testOnBorrow: true
  testOnReturn: true
  jmxEnabled: true
  redisHost: 116.62.50.165
  redisPort: 6379
  timeout: 1000

mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml




alipay:
  callback:
    url: http://116.62.50.165:8080/order/alipay_callback.do
  qrcode:
    path: F:\\workspace_idea\\pr\\img\\
  public:
    key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsjQu/dEXU0qZU3++jrd5ItZIhTvmH9PuIylN4jxeY4qcaf/OVaQ074qd2xl0LDEDh9TA8ZNBwXEVROkDAhOsi6V7emjRCJrlkY0a9XvmPjoxKZ3K2y/laxtktoSw1xY3sXQl9v/rQnlsqSds7Ye9mGLAOvNUAQ/zyaCckjdRYcL3OARaHF/05grc1Q4Y3RvP8MD9F11TuSYRtgi34/m1tVqESRr7OKt3TFL6Zt1bxtri26bc3dzWKIE7C41L2gKZApmNEDzQAzsMJx5hH7YfVUxTc1CgvfTXvYaob7j3hZp3fKan+wBsw9IX1MwxIxxwIDAQAB

token:
  timeout: 10


ftp:
  host: 116.62.50.165
  user: ftpuser
  pass: cx121314