package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    List<Cart> selectByUserId(@Param("userId") Integer userId);

    int updateQualtityByProductId(@Param("productId")Integer productId,@Param("quantity")Integer quantity);

    int totalCountByUnchecked(@Param("userId")Integer userId);

    Cart findCartByUseridAndProductId(@Param("productId")Integer productId,@Param("userId")Integer userId);

    List<Cart> selectByUserIdAndChecked(@Param("userId") Integer userId);

    int deleteBatch(@Param("cartList")List<Cart> cartList);

}